# Generated by Django 6.0.2 on 2026-03-01 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mentor_mother_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('total_green_cases', models.IntegerField(default=0)),
                ('total_blue_cases', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('folder_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muac', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('identified_problem', models.TextField()),
                ('counseling_given', models.TextField()),
                ('demonstration_shown', models.TextField(blank=True, null=True)),
                ('anything_additional', models.TextField(blank=True, null=True)),
                ('problem_faced_by_mm', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCHReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mentor_mother_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('total_green', models.IntegerField(default=0)),
                ('total_blue', models.IntegerField(default=0)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mentor_mother_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('district', models.CharField(max_length=255)),
                ('day_of_week', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('objective', models.TextField()),
                ('observation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
