# Generated by Django 5.2.4 on 2026-03-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregistration',
            name='spss_breastfeeding_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_child_death_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_child_no_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_delivery_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_first_pv_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_immunization_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_lactate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_marital_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_medical_record',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_no_antenatal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_no_postnatal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_number_child_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_number_children_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_number_children_sd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_number_miscarriages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_nutrition_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_pregnant_record',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_rh_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_second_antenatal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_second_breastfeeding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_second_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_second_immunization',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_second_postnatal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_second_preg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_second_pregnancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientregistration',
            name='spss_starting_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
