# Generated by Django 4.2.29 on 2026-03-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_clientfollowup'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientfollowup',
            index=models.Index(fields=['client', 'created_at'], name='records_cli_client__933923_idx'),
        ),
        migrations.AddIndex(
            model_name='clientfollowup',
            index=models.Index(fields=['created_by', 'created_at'], name='records_cli_created_6a648d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientfollowup',
            index=models.Index(fields=['date'], name='records_cli_date_37b71a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientregistration',
            index=models.Index(fields=['created_by', 'created_at'], name='records_cli_created_6dcd48_idx'),
        ),
        migrations.AddIndex(
            model_name='clientregistration',
            index=models.Index(fields=['mentor_mother_name', 'date'], name='records_cli_mentor__448e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientregistration',
            index=models.Index(fields=['folder_number'], name='records_cli_folder__5fdcc2_idx'),
        ),
        migrations.AddIndex(
            model_name='clientregistration',
            index=models.Index(fields=['date'], name='records_cli_date_1d8cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='clientregistration',
            index=models.Index(fields=['name'], name='records_cli_name_247a87_idx'),
        ),
        migrations.AddIndex(
            model_name='mchreport',
            index=models.Index(fields=['created_by', 'created_at'], name='records_mch_created_6a4efa_idx'),
        ),
        migrations.AddIndex(
            model_name='mchreport',
            index=models.Index(fields=['mentor_mother_name', 'date'], name='records_mch_mentor__b086f5_idx'),
        ),
        migrations.AddIndex(
            model_name='mchreport',
            index=models.Index(fields=['date'], name='records_mch_date_a7402d_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['created_by', 'created_at'], name='records_wee_created_ca34fd_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['mentor_mother_name', 'date'], name='records_wee_mentor__8cbdcb_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['date'], name='records_wee_date_a07ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['day_of_week'], name='records_wee_day_of__6fe364_idx'),
        ),
    ]
